sudo: false
language: ruby
script:
   - bundle install
   - bundle exec ensure_arduino_installation.rb
   - echo "Arduino library directory:"
   - bundle exec arduino_library_location.rb
   - wget https://github.com/itead/ITEADLIB_Arduino_Nextion/archive/master.zip
   - unzip -o master.zip
   - mv ITEADLIB_Arduino_Nextion-master $(bundle exec arduino_library_location.rb)
   - bundle exec arduino_ci_remote.rb
