sudo: false
language: ruby
before_install:
   - wget https://github.com/itead/ITEADLIB_Arduino_Nextion/archive/master.zip
   - unzip -o master.zip
   - mkdir -p ~/Arduino/libraries/
   - mv ITEADLIB_Arduino_Nextion-master ~/Arduino/libraries/
script:
   - bundle install
   - bundle exec arduino_ci_remote.rb
